---
abstract: ~
author:
  - 'CMU, re-write for Catalyst by Michael Robbert'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: netreg
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80025
  Config::General: 0
  Moose: 0
  namespace::autoclean: 0
version: 2.01
