package netreg::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'netreg::Schema',
    
);

=head1 NAME

netreg::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<netreg>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<netreg::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.41

=head1 AUTHOR

Robbert, Michael

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
